### ISSUE TITLE
PartitionFormat not working as intented

### ISSUE THREAD

**Issue by ollikaven** [snowplow/snowplow-s3-loader#247]
Version: 2.1.2

For SELF_DESCRIBING events I'm using the example configuration for partitionFormat (except after last slash).
`     
 "partitionFormat": "{vendor}.{name}/model={model}/dt={yy}-{mm}-{dd}",
`
I would assume the first part of the prefix would be e.g.:
 _com.snowplowanalytics.snowplow.badrows.schema_violations/_. 

However, this config will produce prefix. The last part timestamp of sort?
 _com.snowplowanalytics.snowplow.badrows.705000000AM72_

Changing {name} to {schema} works as expected:
`     
 "partitionFormat": "{vendor}.{schema}/model={model}/dt={yy}-{mm}-{dd}",
`
This will create prefix:
 _com.snowplowanalytics.snowplow.badrows.schema_violations/_. 

Maybe this line has something to do with this behaviour?
https://github.com/snowplow/snowplow-s3-loader/blob/master/src/main/scala/com/snowplowanalytics/s3/loader/connector/KinesisS3Emitter.scala#L245

**Comment by istreeter** [comment]
Thanks @ollikaven this is definitely an error!

I think it is an error in the example configuration file, rather than error in the code, i.e. the intended syntax was `{vendor}.{schema}` instead of `{vendor}.{name}`.

I suggest I change it so that both `{schema}` and `{name}` are both valid and both do the same thing.
